### ISSUE TITLE
file descriptor out of range error seen after multiple restarts

### ISSUE THREAD

**Issue by agccie** [agccie/ACI-EnhancedEndpointTracker#4]
After multiple restarts (seen when exceeding max ep jobs), file descriptor out of range errors are seen.  I suspect we're not correctly closing sockets on restarts

3163||UTC 2017-11-25 21:32:01.910||ERROR||ep_subscriber.py:(493)||pending jobs(65537) exceeds max threshold(65536)
3163||UTC 2017-11-25 21:32:01.910||INFO||utils.py:(851)||restarting fabric: /bin/bash ./bash/workers.sh -r CC-LAN

7613||UTC 2017-11-25 22:35:30.345||WARNING||utils.py:(594)||exception occurred in get request: Traceback (most recent call last):
  File "app/tasks/ept/utils.py", line 591, in get
    resp = session.get(turl, timeout=timeout)
  File "app/tasks/tools/acitoolkit/acisession.py", line 820, in get
    resp = self.session.get(get_url, timeout=timeout, verify=self.verify_ssl, proxies=self._proxies, cookies=cookies)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 480, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 370, in send
    timeout=timeout
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 782, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connection.py", line 250, in connect
    ssl_version=resolved_ssl_version)
  File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 301, in ssl_wrap_socket
    rd, _, _ = select.select([sock], [], [], sock.gettimeout())
ValueError: filedescriptor out of range in select()

**Comment by agccie** [comment]
https://github.com/agccie/ACI-EnhancedEndpointTracker/pull/8
